// Code generated by "enumer -type=LabelType"; DO NOT EDIT

package jobs

import (
	"fmt"
)

const _LabelType_name = "unknowncommandschedule"

var _LabelType_index = [...]uint8{0, 7, 14, 22}

func (i LabelType) String() string {
	if i >= LabelType(len(_LabelType_index)-1) {
		return fmt.Sprintf("LabelType(%d)", i)
	}
	return _LabelType_name[_LabelType_index[i]:_LabelType_index[i+1]]
}

var _LabelTypeNameToValue_map = map[string]LabelType{
	_LabelType_name[0:7]:   0,
	_LabelType_name[7:14]:  1,
	_LabelType_name[14:22]: 2,
}

func LabelTypeString(s string) (LabelType, error) {
	if val, ok := _LabelTypeNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LabelType values", s)
}
